### ISSUE TITLE
False positive for "An embedded object must have a text alternative"

### ISSUE THREAD

**Issue by wendyabc** [dequelabs/axe-firefox-devtools#24] opened 2015-08-24 18:14 UTC
Repro steps:
1. Load http://bing.com in Firefox, run the aXe accessibility audit
2. 6 failures of "An embedded object must have a text alternative."

HTML of an example failure: object data="/rms/rms%20answers%20Identity%20Blue$BlueIdentityDropdownBootStrap/jc/afd2a963/04592351.js" height="0" width="0"></object>

Because the height and width are 0, there should be 0 failures for this test.

**Comment by dsturley** [comment] 2015-08-24 20:31
`width=0 height=0` will not reliably hide content from all assistive technologies, due to this aXe does not consider this a sufficient technique. You should use `style="display: none"`, `style="visibility: hidden"` to reliably hide content for all users or `aria-hidden="true"` to hide content from screen readers.

However, if you can find supporting documentation from a standards body that states that `width=0 height=0` SHOULD hide content from assistive technology we will make this change.

**Comment by dylanb** [comment] 2015-08-24 21:22
@dsturley I do not have my Windows machine with me - can you check whether JAWS or NVDA announce these objects in any way?

**Comment by dsturley** [comment] 2015-08-24 22:18
@dylanb Interestingly enough, `<object>` used in this manner are actually treated as frames, so width/height has no effect:

<img width="1037" alt="VoiceOver frames rotor showing blank frame" src="https://cloud.githubusercontent.com/assets/421380/9453908/f2d34046-4a8b-11e5-9979-c758735ba815.png">

It might be worthwhile looking into how this behavior impacts other rules.  The `<object>` element is so 
nebulous in HTML5 that it basically could be anything:

http://www.w3.org/TR/html5/embedded-content-0.html#the-object-element

**Comment by dylanb** [comment] 2015-08-25 15:10
Wendy, as far as we can tell, this specific instance is not a false positive.

However, you have prompted us to want to take a look at this rule in more detail.

I have created an issue here https://github.com/dequelabs/axe-core/issues/124 to track this.

**Comment by dylanb** [comment] 2015-08-27 17:46
@wendyabc after yesterday's discussion, I thought it would be good to put down our rationale for why we don't think we should change the rule to suppress this violation.

Firstly let me say that in your specific case, the issue is minor. In that it does not have any major impact for any user group that would cause them to not be able to use the page.

That being said, the principle we are following is one of "equivalence", in this specific case, a fully able user using a mouse would not in any way be aware that an embedded object is on the page. There is no visual indication and the embedded object does not (as far ase we can tell) emot any sound.

A screen reader user, however, encounters an element that is announced as an iframe. Depending on what the user is doing, or trying to do, the user might think they are missing out on some functionality and might waste time trying to get sighted assistance to determine what they are missing. As I said above, this will (in your specific case) be an irritation.

We equate this very much with an image that is decorative but has no alt attribute.

As I said yesterday, if you have a different interpretation, we would very much like to hear it.

**Comment by wendyabc** [comment] 2015-08-27 18:12
Which screen reader/browser/platform combination announces this as an iframe?

**Comment by dsturley** [comment] 2015-08-27 22:17
Windows 7, Firefox 40, NVDA 2015.3.  Reproducible by using the frame shortcut (NVDA + M or NVDA + SHIFT + M if the frame is backwards in the doc).

It will read the JavaScript code in the embedded object:
```
IFrame
var wln=wln||"";(function(){function n(n){n.style.display="none"}function 
```

**Comment by marcysutton** [comment] 2016-08-29 23:45
I'm going to close this as it was addressed in https://github.com/dequelabs/axe-core/issues/124. Let us know if you encounter any issues!

**Closed by marcysutton** 2016-08-29 23:45 UTC
